apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: billing-service-deployment-poc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app.py
    spec:
      containers:
      - name: billing-service-container
        image: billing-service-poc:v1
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: app.py